# Generated by Django 5.0.4 on 2024-11-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fl_test',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fl_test',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fl_test',
            name='time',
        ),
        migrations.AddField(
            model_name='fl_test',
            name='GPI0_POES',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_POES'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='BTM_VALUE',
            field=models.CharField(default=None, max_length=2048, verbose_name='BTM_VALUE'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='FL_IP',
            field=models.CharField(default=None, max_length=16, verbose_name='FL_IP'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_24V_SM',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_24V_SM'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_BLUE',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_BLUE'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_GREEN',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_GREEN'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LASER_BTM',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LASER_BTM'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LASER_T3D',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LASER_T3D'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LASER_TOP',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LASER_TOP'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LED1',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LED1'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LED2',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LED2'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LED3',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LED3'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_LED4',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_LED4'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPI0_RED',
            field=models.CharField(default=None, max_length=16, verbose_name='GPI0_RED'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='MAC_ADDRESS',
            field=models.CharField(default=None, max_length=16, verbose_name='MAC_ADDRESS'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='TOP_VALUE',
            field=models.CharField(default=None, max_length=2048, verbose_name='TOP_VALUE'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='VERSION',
            field=models.CharField(default=None, max_length=16, verbose_name='VERSION'),
        ),
        migrations.AddField(
            model_name='fl_test',
            name='DATE',
            field=models.DateField(default=None, verbose_name='DATE'),
        ),
        migrations.AddField(
            model_name='fl_test',
            name='ID',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='fl_test',
            name='TIME',
            field=models.TimeField(default=None, verbose_name='TIME'),
        ),
    ]
