# Generated by Django 5.0.4 on 2024-11-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0003_remove_fl_test_gpi0_24v_sm_remove_fl_test_gpi0_blue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fl_test',
            name='FL_IP',
            field=models.CharField(default=None, max_length=32, verbose_name='FL_IP'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='MAC_ADDRESS',
            field=models.CharField(default=None, max_length=32, verbose_name='MAC_ADDRESS'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='VERSION',
            field=models.CharField(default=None, max_length=32, verbose_name='VERSION'),
        ),
    ]
