# Generated by Django 5.0.4 on 2024-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0004_alter_fl_test_fl_ip_alter_fl_test_mac_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_24V_SM',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_24V_SM'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_BLUE',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_BLUE'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_GREEN',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_GREEN'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LASER_BTM',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LASER_BTM'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LASER_T3D',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LASER_T3D'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LASER_TOP',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LASER_TOP'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LED1',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LED1'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LED2',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LED2'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LED3',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LED3'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_LED4',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_LED4'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_POES',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_POES'),
        ),
        migrations.AlterField(
            model_name='fl_test',
            name='GPIO_RED',
            field=models.CharField(default=None, max_length=32, verbose_name='GPIO_RED'),
        ),
    ]
