# Generated by Django 5.0.4 on 2024-11-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0005_alter_fl_test_gpio_24v_sm_alter_fl_test_gpio_blue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laser_data',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default=None, verbose_name='DATE')),
                ('TIME', models.TimeField(default=None, verbose_name='TIME')),
                ('MAC_ADDRESS', models.CharField(default=None, max_length=32, verbose_name='MAC_ADDRESS')),
                ('TOP_VALUE', models.CharField(default=None, max_length=2048, verbose_name='TOP_VALUE')),
                ('BTM_VALUE', models.CharField(default=None, max_length=2048, verbose_name='BTM_VALUE')),
            ],
        ),
        migrations.CreateModel(
            name='Voltage_data',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default=None, verbose_name='DATE')),
                ('TIME', models.TimeField(default=None, verbose_name='TIME')),
                ('MAC_ADDRESS', models.CharField(default=None, max_length=32, verbose_name='MAC_ADDRESS')),
                ('voltage3v3', models.CharField(default=None, max_length=32, verbose_name='voltage3v3')),
                ('voltage3d', models.CharField(default=None, max_length=32, verbose_name='voltage3d')),
                ('voltage24s', models.CharField(default=None, max_length=32, verbose_name='voltage24s')),
                ('voltage48', models.CharField(default=None, max_length=32, verbose_name='voltage48')),
                ('voltage24lower', models.CharField(default=None, max_length=32, verbose_name='voltage24lower')),
                ('voltage24upper', models.CharField(default=None, max_length=32, verbose_name='voltage24upper')),
            ],
        ),
    ]
