# Generated by Django 5.0.4 on 2024-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicoMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateField(default=None, verbose_name='date')),
                ('time', models.TimeField(default=None, verbose_name='time')),
                ('photoeye', models.CharField(max_length=16, verbose_name='photoeye')),
                ('computer', models.CharField(max_length=16, verbose_name='computer')),
                ('poe_sw', models.CharField(max_length=16, verbose_name='poe_sw')),
                ('channel0', models.CharField(max_length=16, verbose_name='channel0')),
                ('channel1', models.CharField(max_length=16, verbose_name='channel1')),
                ('channel2', models.CharField(max_length=16, verbose_name='channel2')),
                ('channel3', models.CharField(max_length=16, verbose_name='channel3')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
            ],
        ),
    ]
