# Generated by Django 5.0.4 on 2024-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picoweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picomaster',
            name='humidity',
            field=models.CharField(default=None, max_length=64, verbose_name='humidity'),
        ),
        migrations.AddField(
            model_name='picomaster',
            name='temper',
            field=models.CharField(default=None, max_length=64, verbose_name='temper'),
        ),
    ]
